name: ci

on:
  - push
  - pull_request

jobs:
  build:
    name: ${{ matrix.kind }} ${{ matrix.os }} ${{ matrix.node }}
    runs-on: ${{ matrix.os }} ${{ matrix.node }}
    strategy:
      matrix:
        os:
          - macOS-latest
          - ubuntu-latest
          - windows-latest
        node:
          - 14
          - 16
          - 18

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Setup pnpm
        uses: pnpm/action-setup
        with:
          pnpm: latest

      - name: Setup Node ${{ matrix.node }}
        uses: action/setup-node@v3
        with:
          node-version: ${{ matrix.node }}
          cache: pnpm

      - name: Install Dependencies
        run: pnpm i

      - name: Lint
        run: pnpm lint

      - name: Type Coverage
        run: pnpm typecov
